name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build APK
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug
